routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ForumQuestionController@index')->name('top');

Route::resource('questions', 'ForumQuestionController', ['only' => ['create', 'store', 'show', 'edit', 'update', 'destroy']]);

Route::resource('answers', 'ForumAnswerController', ['only' => ['store', 'show', 'edit', 'update', 'destroy']]);

Route::post('/search', 'SearchController@index')->name('search');

Route::get('/myquestions','SearchController@myquestions')->name('myquestions');

Route::get('/myanswers','SearchController@myanswers')->name('myanswers');

Route::get('/myquestions_guest','SearchController@myquestions_guest')->name('myquestions_guest');

Route::get('/myanswers_guest','SearchController@myanswers_guest')->name('myanswers_guest');

Route::get('/tags','SearchController@tags')->name('tags');

Route::get('/tag_question/{id}','SearchController@tag_question')->name('tag_question');

Route::post('/best_answer','BestAnswer@post')->name('best');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts/app')

@section('content')

    <div class="container mt-4">
        @auth
            <div id="userinfo_box">
                <div id="image_box">
                    <img id="user-icon" src="{{asset('storage/post_images/'.auth()->user()->image_url,true)}}"></img>
                </div>
                <div id="name_box">
                    <p>{{auth()->user()->name}}</p>
                </div>
            </div>
            <a href={{url('myquestions')}}>
                <p>My Questions</p>
            </a>
            <a href={{url('myanswers')}}>
                <p>My Ansewrs</p>
            </a>
        @endauth
        
        @guest
            <div id="userinfo_box">
                <div id="image_box">
                    <img id="user-icon" src="https://art-laravel.lolipop.io/storage/post_images/BuwtwhjxO0OKj7Zsn7EM8aOWp59NqlHkqNyeUa4D.jpeg"></img>
                </div>
                <div id="name_box">
                    <p>{{"guest user"}}</p>
                </div>
                
            <a href={{url('myquestions_guest')}}>
                <p>My Questions</p>
            </a>
            <a href={{url('myanswers_guest')}}>
                <p>My Ansewrs</p>
            </a>
                
            </div>
        @endguest
        
        {{--common--}}
            <a href={{url('tags')}}>
                <p>Tags</p>
            </a>
        
        <div class="mb-4">
            <a href="{{ route('questions.create') }}" class="btn btn-primary">
            投稿を新規作成する
            </a>
        </div>
        @forelse ($questions as $question)
            <div class="card mb-4">
                <div class="card-header">
                    <img class="list-icon" height="30px" src="{{asset('storage/post_images/'.$question->user->image_url,true)}}"></img>
                    <p>{{$question->user->name}}</p>
                    {{ $question->title }}
                </div>
                <div class="card-body">
                    <p class="card-text">
                        {!! nl2br(e(str_limit($question->question_comment, 200))) !!}
                    </p>
                    <a class="card-link" href="{{ route('questions.show', ['question' => $question]) }}">
                        続きを読む
                    </a>
                </div>
                <div class="card-footer">
                    <span class="mr-2">
                        投稿日時 {{ $question->created_at->format('Y.m.d') }}
                    </span>

                    @if ($question->answers()->count())
                        <span class="badge badge-primary">
                            コメント {{ $question->answers()->count() }}件
                        </span>
                    @endif
                </div>
            </div>
        @empty
            <p>投稿がありません</p>
        @endforelse
    </div>
    <div class="d-flex justify-content-center mb-5">
        {{ $questions->links() }}
    </div>
@endsection