routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ForumQuestionController@index')->name('top');

Route::resource('questions', 'ForumQuestionController', ['only' => ['create', 'store', 'show', 'edit', 'update', 'destroy']]);

Route::resource('answers', 'ForumAnswerController', ['only' => ['store', 'show', 'edit', 'update', 'destroy']]);

Route::post('/search', 'SearchController@index')->name('search');

Route::get('/myquestions','SearchController@myquestions')->name('myquestions');

Route::get('/myanswers','SearchController@myanswers')->name('myanswers');

Route::get('/myquestions_guest','SearchController@myquestions_guest')->name('myquestions_guest');

Route::get('/myanswers_guest','SearchController@myanswers_guest')->name('myanswers_guest');

Route::get('/tags','SearchController@tags')->name('tags');

Route::get('/tag_question/{id}','SearchController@tag_question')->name('tag_question');

Route::post('/best_answer','BestAnswer@post')->name('best');

resources/views/answers/edit.blade.php
@extends('layouts/layout')

@section('content')
    <div class="container mt-4">
        <div class="border p-4">
            <h1 class="h5 mb-4">
                質問の編集
            </h1>

            <form method="POST" action="{{ route('answers.update' , ['answer' => $answer]) }}">
                @csrf
                @method('PUT')

                <fieldset class="mb-4">
                    <div class="form-group">
                        <label for="answers_comment">
                            本文
                        </label>

                        <textarea
                            id="answers_comment"
                            name="answers_comment"
                            class="form-control {{ $errors->has('answers_comment') ? 'is-invalid' : '' }}"
                            rows="4"
                        >{{ old('answers_comment') ?: $answer->answers_comment }}</textarea>
                        @if ($errors->has('answers_comment'))
                            <div class="invalid-feedback">
                                {{ $errors->first('answers_comment') }}
                            </div>
                        @endif
                    </div>

                    <div class="mt-5">
                        <a class="btn btn-secondary" href="{{ route('questions.show', ['answer' => $answer]) }}">
                            キャンセル
                        </a>

                        <button type="submit" class="btn btn-primary">
                            更新する
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
@endsection