routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'ForumQuestionController@index')->name('top');

Route::resource('questions', 'ForumQuestionController', ['only' => ['create', 'store', 'show', 'edit', 'update', 'destroy']]);

Route::resource('answers', 'ForumAnswerController', ['only' => ['store', 'show', 'edit', 'update', 'destroy']]);

Route::post('/search', 'SearchController@index')->name('search');

Route::get('/myquestions','SearchController@myquestions')->name('myquestions');

Route::get('/myanswers','SearchController@myanswers')->name('myanswers');

Route::get('/myquestions_guest','SearchController@myquestions_guest')->name('myquestions_guest');

Route::get('/myanswers_guest','SearchController@myanswers_guest')->name('myanswers_guest');

Route::get('/tags','SearchController@tags')->name('tags');

Route::get('/tag_question/{id}','SearchController@tag_question')->name('tag_question');

Route::post('/best_answer','BestAnswer@post')->name('best');

resources/views/questions/create.blade.php
@extends('layouts/layout')

@section('content')

    <div class="container mt-4">
        <div class="border p-4">
            <h1 class="h5 mb-4">
                質問を投稿する
            </h1>
            <form method="POST" action="{{ route('questions.store') }}" enctype="multipart/form-data">
                @csrf
                <fieldset class="mb-4">
                    <div class="form-group">
                        <label for="title">
                            タイトル
                        </label>
                        <input
                            id="title"
                            name="title"
                            class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                            value="{{ old('title') }}"
                            type="text"
                        >
                        @if ($errors->has('title'))
                            <div class="invalid-feedback">
                                {{ $errors->first('title') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="question_comment">
                            本文
                        </label>
                        <textarea
                            id="question_comment"
                            name="question_comment"
                            class="form-control {{ $errors->has('question_comment') ? 'is-invalid' : '' }}"
                            rows="4"
                        >{{ old('question_comment') }}</textarea>
                        @if ($errors->has('question_comment'))
                            <div class="invalid-feedback">
                                {{ $errors->first('question_comment') }}
                            </div>
                        @endif
                        <div class="form-group">
                          <label for="tag">タグ</label>
                          <select class="form-control" id="tag_1" name="tag_1">
                            <option value="">-</option>
                            @forelse ($tags as $tag)                            
                            <option value="{{$tag->id}}">{{$tag->name}}</option>
                            @empty

                            @endforelse
                          </select>
                        </div>
                        
                        <div class="form-group">
                            <label for="FormControlFile_i">画像ファイルを選択してください</label>
                            <input type="file" name=image_url class="form-control-file" id="FormControlFile_i">
                            <label for="FormControlFile_a">音声ファイルを選択してください</label>
                            <input type="file" name=audio_url class="form-control-file" id="FormControlFile_a">
                            <label for="FormControlFile_v">動画ファイルを選択してください</label>
                            <input type="file" name=video_url class="form-control-file" id="FormControlFile_v">
                            <input type="hidden" name=video_url_uped id="hidden_video_url">
                        </div>
                    
                    </div>
                    <div class="mt-5">
                        <a class="btn btn-secondary" href="{{ route('top') }}">
                            キャンセル
                        </a>

                        <button type="submit" class="btn btn-primary">
                            投稿する
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>


<script src="https://www.gstatic.com/firebasejs/5.9.1/firebase.js"></script>

<!-- Firebase App is always required and must be first -->
<script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-storage.js"></script>

<script>
  // Initialize Firebase
  // TODO: Replace with your project's customized code snippet
  var config = {
    apiKey: "AIzaSyC84ZCm1RjRRy_VK7spL-31CRB8QEJtC78",
    authDomain: "<PROJECT_ID>.firebaseapp.com",
    databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
    projectId: "lara-art",
    storageBucket: "gs://lara-art.appspot.com/",
    messagingSenderId: "<SENDER_ID>",
  };
  
  firebase.initializeApp(config);
 

// setfileインスタンスを作成
const setfile = document.getElementById("FormControlFile_v");
// CloudStorageインスタンスを作成
const storage = firebase.storage();


// submitで処理開始
setfile.addEventListener('change', e => {
    var file = e.target.files;
    // fileの名前を取得
    file_name = file[0].name;
    // blob形式に変換
    blob = new Blob(file, { type: "video/mpeg" });

    // ページ遷移をなくす
    e.preventDefault();

    // storageのarea_imagesへの参照を定義
    var uploadRef = storage.ref('videos/').child(file_name);


    uploadRef.put(blob).then(snapshot => {
        console.log(snapshot.state);
        var progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        console.log('Upload is ' + progress + '% done');
        // アップロードしたファイルのurlを取得
        uploadRef.getDownloadURL().then(url => {

            // g_url = url;
            console.log(url);
            
            $('#hidden_video_url').val(url);
            
                        console.log($('#hidden_video_url').val());
            
            
            
            
            
            
            
        }).catch(error => {
            console.log(error);
        });
    });
    // valueリセットする
    file_name = '';
    blob = '';
});
  
  
</script>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts/layout')

@section('content')
    <div class="container mt-4">
        <div class="border p-4">
            <h1 class="h5 mb-4">
                質問の編集
            </h1>

            <form method="POST" action="{{ route('questions.update' , ['question' => $question]) }}">
                @csrf
                @method('PUT')

                <fieldset class="mb-4">
                    <div class="form-group">
                        <label for="title">
                            タイトル
                        </label>
                        <input
                            id="title"
                            name="title"
                            class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                            value="{{ old('title') ?: $question->title }}"
                            type="text"
                        >
                        @if ($errors->has('title'))
                            <div class="invalid-feedback">
                                {{ $errors->first('title') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <label for="question_comment">
                            本文
                        </label>

                        <textarea
                            id="question_comment"
                            name="question_comment"
                            class="form-control {{ $errors->has('question_comment') ? 'is-invalid' : '' }}"
                            rows="4"
                        >{{ old('question_comment') ?: $question->question_comment }}</textarea>
                        @if ($errors->has('question_comment'))
                            <div class="invalid-feedback">
                                {{ $errors->first('question_comment') }}
                            </div>
                        @endif
                    </div>

                    <div class="mt-5">
                        <a class="btn btn-secondary" href="{{ route('questions.show', ['question' => $question]) }}">
                            キャンセル
                        </a>

                        <button type="submit" class="btn btn-primary">
                            更新する
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts/app')

@section('content')
    <div class="container mt-4">
        <div class="border p-4">
            <div class="mb-4 text-right">
                <a class="btn btn-primary" href="{{ route('questions.edit' , ['question' => $question])}}">
                編集
                </a>
                
                <form
                    style="display: inline-block;"
                    method="POST"
                    action="{{ route('questions.destroy', ['question' => $question]) }}"
                    >
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">削除</button>
                </form>
            </div>
            
            <img class="list-icon" height="70px" src="{{asset('storage/post_images/'.$question->user->image_url,true)}}"></img>
            <p>{{$question->user->name}}</p>
            
            <h1 class="h5 mb-4">
                {{ $question->title }}
            </h1>

            <p class="mb-5">
                {!! nl2br(e($question->question_comment)) !!}
            </p>
            
            @forelse ($question->tagRelation()->get() as $tag_relation)            
                <p class="mb-3">タグ：
                    <a href="{{url('tag_question',$tag_relation->tag->id)}}">
                    {{$tag_relation->tag->name}}
                    </a>
                </p>
            
            @empty
                {{--タグなし--}}
            @endforelse
            
            @forelse ($question->contents()->get() as $content)
                @if($content->content_type == 1) 
                    <img src="{{asset('storage/'.$content->content_url, true)}}" alt="no_image" class="img-thumbnail">
                @elseif($content->content_type == 2)
                    <audio src="{{asset('storage/'.$content->content_url, true)}}" controls>
                @elseif($content->content_type == 3)
                    <video src="{{$content->content_url}}" height="300px" controls type="video/mp3"></video>
                @endif
            @empty
                {{--コンテンツなし--}}
            @endforelse
            <form class="mb-4" method="POST" action="{{ route('answers.store') }}">
                @csrf
                <input
                    name="question_id"
                    type="hidden"
                    value="{{ $question->id }}"
                >
                <div class="form-group">
                    <label for="answers_comment">
                        本文
                    </label>
                    <textarea
                        id="answers_comment"
                        name="answers_comment"
                        class="form-control {{ $errors->has('answers_comment') ? 'is-invalid' : '' }}"
                        rows="4"
                    >{{ old('answers_comment') }}</textarea>
                    @if ($errors->has('answers_comment'))
                    <div class="invalid-feedback">
                        {{ $errors->first('answers_comment') }}
                    </div>
                    @endif
                </div>
                <div class="mt-4">
                    <button type="submit" class="btn btn-primary">
                        コメントする
                    </button>
                </div>
            </form>
            <section>
                <h2 class="h5 mb-4">
                    コメント
                </h2>
                @forelse($question->answers()->get() as $forum_answer)
                    <div class="border-top p-4">
                        <img class="list-icon" height="30px" src="{{asset('storage/post_images/'.$question->user->image_url,true)}}"></img>
                        <p>{{$forum_answer->user->name}}</p>
                        <time class="text-secondary">
                            {{ $forum_answer->created_at->format('Y.m.d H:i') }}
                        </time>
                        <p class="mt-2">
                            {!! nl2br(e($forum_answer->answers_comment)) !!}
                        </p>
                        
                        <form action="{{route('best')}}" method="POST">
                            @csrf
                            <!--<button class="btn btn-danger btn-sm">ベストアンサー</button>-->
                            <button class="best-ans-button">

                            @if($forum_answer->best_answer_flg==1)
                            
                                <i class="fas fa-crown crown-on"></i>
                            @else
                                <i class="fas fa-crown crown-off"></i>
                            @endif
                            </button>
                            <input type="hidden" name="hidden_answer_id" value="{{$forum_answer->id}}"/>
                        </form>
                        
                        <a class="btn btn-primary btn-sm" href="{{ route('answers.edit', ['answer' => $forum_answer])}}">
                            編集
                        </a>
                        

                        
                        <form
                            style="display: inline-block;"
                            method="POST"
                            action="{{ route('answers.destroy', ['answer' => $forum_answer]) }}"
                            >
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm">削除</button>
                        </form>
                    </div>
               @empty
                    <p>コメントはまだありません。</p>
                @endforelse
            </section>
        </div>
    </div>
@endsection